# basic server setup

# due to the problem with fedora 41 using dnf5 but it doesnt have python3-libdnf5 which is required by ansible we can use dnf4 as a backup to install it
- name: Install python3-libdnf5 if missing
  ansible.builtin.dnf:
    use_backend: dnf4
    name: python3-libdnf5
    state: present

- name: Update packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true

- name: Install fail2ban
  ansible.builtin.dnf:
    name: fail2ban
    state: present

- name: Add fail2ban filter definition
  ansible.builtin.copy:
    src: files/nginx-errors.conf
    dest: /etc/fail2ban/filter.d/
    owner: root
    group: root
    mode: "0644"

- name: Confiure fail2ban local.jail
  ansible.builtin.copy:
    src: files/jail.local
    dest: /etc/fail2ban/
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload fail2ban config

- name: Enable and start fail2ban
  ansible.builtin.service:
    name: fail2ban
    enabled: true
    state: started
