# installs and configures nginx
- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
- name: Copy Nginx site config to sites-enabled
  ansible.builtin.template:
    src: templates/site-config.j2
    dest: "/etc/nginx/conf.d/{{ full_domain }}.conf"
    owner: root
    group: root
    mode: "0644"
- name: Create directory for the site files
  ansible.builtin.file:
    path: /var/www/{{ full_domain }}/html/
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Reload nginx config
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
